[project]
name = "micrograd"
version = "0.1.0"
description = "A tiny scalar-valued automatic differentiation engine and neural net library on top of it with PyTorch-like API"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "graphviz>=0.21",
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
]

[dependency-groups]
dev = [
    "nbstripout>=0.9.1",
]
test = [
    "pytest>=9.1.1",
    "torch>=2.13.0",
]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]
